export const products = [
  {
    id: 'canvas-tote',
    name: 'Everyday Canvas Tote',
    category: 'Accessories',
    price: 28,
    description: 'A sturdy, roomy carryall for market mornings and everything after.',
    color: 'clay',
    symbol: '✳',
    label: 'Bestseller',
  },
  {
    id: 'stoneware-mug',
    name: 'Sunday Stoneware Mug',
    category: 'Home',
    price: 24,
    description: 'Hand-finished stoneware that makes the first cup feel like a ritual.',
    color: 'sage',
    symbol: '◒',
    label: 'Small batch',
  },
  {
    id: 'linen-throw',
    name: 'Soft Landing Linen Throw',
    category: 'Home',
    price: 86,
    description: 'An airy, textured layer made for slow mornings and open windows.',
    color: 'blue',
    symbol: '〰',
    label: '',
  },
  {
    id: 'daily-notebook',
    name: 'The Daily Notebook',
    category: 'Stationery',
    price: 18,
    description: 'A good place for big plans, tiny lists, and all the in-between.',
    color: 'butter',
    symbol: '✎',
    label: 'Made to last',
  },
  {
    id: 'glass-carafe',
    name: 'Ripple Glass Carafe',
    category: 'Home',
    price: 42,
    description: 'A sculptural everyday carafe with a satisfying ripple grip.',
    color: 'lilac',
    symbol: '♧',
    label: '',
  },
  {
    id: 'weekend-cap',
    name: 'Weekend Cotton Cap',
    category: 'Accessories',
    price: 32,
    description: 'Soft washed cotton and a just-right brim for sunny detours.',
    color: 'peach',
    symbol: '⌒',
    label: '',
  },
  {
    id: 'pocket-pens',
    name: 'Pocket Pen Set',
    category: 'Stationery',
    price: 16,
    description: 'Three smooth-writing pens to keep close wherever ideas happen.',
    color: 'mint',
    symbol: '✐',
    label: 'Customer favorite',
  },
  {
    id: 'market-bowl',
    name: 'Gathering Bowl',
    category: 'Home',
    price: 54,
    description: 'A versatile, hand-glazed bowl that earns its place on the table.',
    color: 'rose',
    symbol: '◡',
    label: 'Small batch',
  },
]
